server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: users-status-check
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/users/status/check
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - AuthorizationHeaderFilter

      - id: users-ws-login
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/users/login
        - Method=POST
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: users-ws
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/individualCustomers/save
        - Method=POST
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: users-ws
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/corporateCustomers/save
        - Method=POST
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: users-ws-get-update-delete
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/individualCustomers/*
        - Method=PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - AuthorizationHeaderFilter

      - id: users-ws-get
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/individualCustomers/*
        - Method=GET
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: users-ws-get-update-delete
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/corporateCustomers/*
        - Method=PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - AuthorizationHeaderFilter

      - id: users-ws-get
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/corporateCustomers/*
        - Method=GET
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: rentals-ws-all
        uri: lb://rentals-ws
        predicates:
        - Path=/rentals-ws/rentaltypes
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/rentals-ws/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost       
token:
  secret: mysupersecretkeymysupersecretkeymysupersecretkey